//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeatcherCRUD_Scafolding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teatcher
    {
        public int TeatcherId { get; set; }
        public string TeatcherName { get; set; }
        public Nullable<decimal> TeatcherSalary { get; set; }
        public string TeatcherCity { get; set; }
    }
}
